### ISSUE TITLE
pymodbus\server\asynchronous.py\StartSerialServer: TypeError: __init__() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by shishir-dey** [riptideio/pymodbus#580] opened 2021-01-02 06:49 UTC
### Versions

* Python: 3.7
* OS: Windows 10
* Pymodbus: 2.4.0
* Modbus Hardware: CP210x USB to UART Bridge connected to a Modbus Master device

### Pymodbus Specific

* Server: rtu - async

### Description

The program crashes.

Seems like ```twisted.internet.serialport.SerialPort``` does not have a ```timeout``` parameter. See https://twistedmatrix.com/documents/15.4.0/api/twisted.internet.serialport.SerialPort.html

### Code and Logs

Code:
```python
StartSerialServer(self.context, identity=self.identity,
                        port=GetSerialPort(), framer=ModbusRtuFramer, baudrate=38400)
```

Logs:
```python
2021-01-02 12:14:25,274 Thread-1        INFO     asynchronous   :327      Starting Modbus Serial Server on COM8
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\x\Downloads\Modbus Slave\tick.py", line 15, in run
    self.callback()
  File "C:\Users\x\Downloads\Modbus Slave\app.py", line 183, in modbus_server_task
    port=GetSerialPort(), framer=ModbusRtuFramer, baudrate=38400)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37\lib\site-packages\pymodbus\server\asynchronous.py", line 340, in StartSerialServer
    rtscts=rtscts, bytesize=bytesize)
TypeError: __init__() got an unexpected keyword argument 'timeout'
```

**Comment by dhoomakethu** [comment] 2021-01-02 06:52
This should be fixed with 2.4.0. what version of pymodbus is this

**Comment by dhoomakethu** [comment] 2021-01-02 06:53
You can also give a try with 2.5.0rc2

**Comment by jhfatehi** [comment] 2021-01-14 07:46
I am running pymodbus 2.4.0 and got the same error.  I resolved it by removing the 'timeout' kwarg from line 339 in pymodbus/server/asynchronous.py.

**Comment by shishir-dey** [comment] 2021-01-14 10:46
> I am running pymodbus 2.4.0 and got the same error. I resolved it by removing the 'timeout' kwarg from line 339 in pymodbus/server/asynchronous.py.

I tried a similar workaround and the server works fine after that. Pymodbus version is 2.4.0.

**Comment by dhoomakethu** [comment] 2021-01-14 12:56
Did you guys tried 2.5.0rc2?

**Comment by cti-jsweet** [comment] 2021-02-19 12:02
@dhoomakethu checked this issue that I was having and it looks like the 2.5.0rc2 fixed the issue for me

**Comment by cti-jsweet** [comment] 2021-02-19 12:14
Doing some testing today on 2.5.0rc2 I'll try to update with my results.

**Comment by dhoomakethu** [comment] 2021-03-02 14:11
@shishir-dey I am not able to reproduce this issue, could you please paste the output of `pip freeze` of your python environment?

**Closed** 2021-03-03 10:03 UTC
Labels: More Information Required
