### ISSUE TITLE
Serial + Async + RTU: Callback is never fired

### ISSUE THREAD

**Issue by submerged15** [riptideio/pymodbus#160] opened 2017-04-30 12:07 UTC
Hi again,

I'm using pymodbus over RS485 with RtuFramer and AsyncModbusProtocol based on the twisted serialport. (Python 2.7)

The callback of the method transaction/ModbusRtuFramer/processIncomingPacket is never fired. In this case the method async/ModbusClientProtocol/_handleresponse.

Workaround: Derivate the ModbusClientProtocol, override the dataReceived method and insert the complete content of the processsIncomingPacket method and replace the callback with the actual method _handleresponse.

**Comment by dhoomakethu** [comment] 2017-05-12 02:46
If you have a working solution could you please raise a PR, so that it could be reviewed and merged if necessary?
Thanks

**Comment by wexi** [comment] 2017-05-18 05:01
I probably encounter the same problem with long RTU queries. It is not "firing" since client/async.py dataReceived() receives incomplete data. Indeed, serial.Serial is using non blocking timeout=0, so why would we receive the complete packet if it is long... 
I will try to use timeout=None with a short inter_byte_timeout and report if I am successful.

**Comment by dhoomakethu** [comment] 2017-05-18 12:39
I believe with the latest release 1.3.0rc1, the issue should be fixed. Just give a try and update your findings.

**Comment by wexi** [comment] 2017-05-18 19:35
Thanks, however with pymodbus-1.3.0rc1 I encounter the following unhandled error.

 ~~~~
   File "/home/wexi/.local/lib/python2.7/site-packages/pymodbus/client/async.py", line 93, in dataReceived
     self.framer.processIncomingPacket(data, self._handleResponse)
   File "/home/wexi/.local/lib/python2.7/site-packages/pymodbus/transaction.py", line 604, in processIncomingPacket
     self._process(callback, error=True)
   File "/home/wexi/.local/lib/python2.7/site-packages/pymodbus/transaction.py", line 631, in _process
     raise ModbusIOException("Unable to decode request")
 pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
~~~~

**Comment by dhoomakethu** [comment] 2017-05-19 03:01
@wexi do see this error always ? I am not able to reproduce this at my end. Could you give more info regarding your setup ?

**Comment by wexi** [comment] 2017-05-19 18:33
I solved my problem by simplifying/correcting transaction.py processIncomingPacket(self, data, callback). I can't say that I am satisfied: With a given Modbus query the normal response length is known in advance and this information is not utilized. To your question, I am using the Kivy modified twisted reactor. My OS is Ubuntu. Thanks.

[patch.txt](https://github.com/riptideio/pymodbus/files/1015176/patch.txt)

**Comment by wexi** [comment] 2017-05-27 18:06
Adding to my previous comment regarding async RTU (improper repacking, a criticism which still stands):

To add timeout protection to async RTU we have to addTimeout() to the deferred.
addTimeout, when fired, causes a CancelledError response errback.
**It is pymodbus responsibility** then to remove the transaction from its FifoTransactionManager instance, which it doesn't... bad things then happen, need I explain?

As far as async RTU is concerned we are not at RC quality yet. Please fix :-)

**Comment by dhoomakethu** [comment] 2017-05-27 21:07
If you think you have a working solution for this issue, could you please
raise a PR ?

ಮೇ 27, 2017 11:36 ಅಪರಾಹ್ನ ರಂದು, "Enoch" <notifications@github.com> ಅವರು
ಬರೆದಿದ್ದಾರೆ:

**Comment by wexi** [comment] 2017-05-27 21:28
A proper solution for the addTimeout() bug requires pymodbus to supply a canceller function during the construction of its deferred. This canceller should remove the transaction from the appropriate manager. Since **I am only interested in async RTU now** I took a shortcut. I leave it for those with write access to this repository (aka the maintainers) to do the hard work.

Again, processIncomingPacket(), also requires a rewrite...

**Comment by dhoomakethu** [comment] 2017-05-27 21:55
Thanks for the hints. I do not mind adding more contributors to the
project. Let me know if you need write access to the repo. Anyhow, You can
always fork and raise a PR upstream. This is a community driven project and
more helping hands are highly appreciated.

ಮೇ 28, 2017 2:58 ಪೂರ್ವಾಹ್ನ ರಂದು, "Enoch" <notifications@github.com> ಅವರು
ಬರೆದಿದ್ದಾರೆ:

A proper solution for the addTimeout() bug requires pymodbus to supply a
canceller function during the construction of its deferred. This canceller
should remove the transaction from the appropriate manager. Since *I am
only interested in async RTU now* I took a shortcut. I leave it for those
with write access to this repository (aka the maintainers) to do the hard
work.

Again, processIncomingPacket(), also requires a rewrite...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/riptideio/pymodbus/issues/160#issuecomment-304477512>,
or mute the thread

**Comment by bhagn** [comment] 2017-10-14 07:28
@submerged15, @wexi can you share the code that instantiates the async client? Is the reactor running in its own thread?

**Comment by wexi** [comment] 2017-10-14 08:30
You are welcome to examine my 'local' branch:
https://github.com/wexi/pymodbus/tree/local
See Foreword in README.rst

**Comment by rahulraghu94** [comment] 2018-01-04 07:11
Hello, I'm unable to reproduce this problem as of the new `pymodbus 1.4.0` release and will be closing this now.

If you are still facing this issue, feel free to reopen this and make sure you leave your **code excerpts**, **logs**, **expected outputs** and anything else that can help us track the problem.

Thanks :)

**Closed by rahulraghu94** 2018-01-04 07:11 UTC
Labels: Enhancments, help wanted
